// Code generated by ogen, DO NOT EDIT.

package opensearch

// OperationName is the ogen operation name
type OperationName = string

const (
	IndexSearchPostOperation OperationName = "IndexSearchPost"
)
