// Code generated by ogen, DO NOT EDIT.

package opensearch

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// IndexSearchPost implements POST /{index}/_search operation.
//
// Поиск логов по trace_id.
//
// POST /{index}/_search
func (UnimplementedHandler) IndexSearchPost(ctx context.Context, req OptIndexSearchPostReq, params IndexSearchPostParams) (r *SearchResponse, _ error) {
	return r, ht.ErrNotImplemented
}
